### ISSUE TITLE
Testing website not saving excluded names.

### ISSUE THREAD

**Issue by AsakaJX** [aticie/ronnia-web#13]
As the title says, when I writing name and saving settings user is still can request maps and on the actual website there's no excluded users in it.

**Comment by aticie** [comment]
Did you press Save button after adding users to list?

**Comment by AsakaJX** [comment]
Sorry for late answer, I was a little busy, yes I ofcourse pressed save button.

**Comment by aticie** [comment]
Noone else complained about this, I don't remember fixing this though. The website had some changes happened since. Probably fixed.
